// SPDX-FileCopyrightText: 2026 Sebastian Kügler <sebas@kde.org>
//
// SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

// The verifier is the last thing between a DJ's real library metadata and
// a zip they upload to a stranger. Until now the only thing exercising it
// was the `verify_anonymized_export` tool pointed at the committed
// fixture -- which is already clean, so the tool had only ever run its
// happy path. Nothing had ever shown it refusing anything.
//
// A gate that has never been seen to close is not known to close. So each
// case here plants a specific leak in a copy of the fixture and asserts
// the verifier catches that leak, plus one case asserting the clean copy
// still passes.
//
// That last premise no longer holds, and the fixture is the reason. It was
// exported by Seabass 0.6, whose anonymizer overwrote rows without
// compacting the files afterwards, so the pre-scrub values are still
// legible in engine/Database2/m.db (52 real artist names) and in
// rekordbox/export.pdb (403). The reader-based checks cannot see them --
// they read live rows, which are correctly scrubbed -- and the byte sweep
// can. Those two files are listed below as a known baseline so the rest of
// the suite still means something; regenerating the fixture from the
// originating sticks is what removes them, and this test will say so when
// it happens.
#include <cassert>

#if !defined(_WIN32)
#include <unistd.h>
#endif
#include <cstdint>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "infrastructure/anonymization_byte_sweep.hpp"
#include "infrastructure/anonymization_verifier.hpp"
#include "infrastructure/rekordbox/kaitai_rekordbox_reader.hpp"
#include "infrastructure/rekordbox/pdb_row_writer.hpp"

#include "scratch_path.hpp"

namespace fs = std::filesystem;
using namespace seabass;

namespace
{

// The two files in the committed fixture that are known to still hold
// real data. Delete this list, and the uses of it, once the fixture has
// been regenerated by a build whose anonymizer compacts what it scrubs.
const std::vector<std::string> knownDirtyFixtureFiles = {
    "engine/Database2/m.db",
    "rekordbox/rekordbox/export.pdb",
};

// Problems other than the known baseline, which are the ones a case is
// actually asserting something about.
std::vector<std::string> beyondKnownBaseline(const std::vector<std::string> &problems)
{
    std::vector<std::string> rest;
    for (const auto &p : problems) {
        const bool known = p.find("still has readable text in its raw bytes") != std::string::npos
            && std::any_of(knownDirtyFixtureFiles.begin(), knownDirtyFixtureFiles.end(),
                           [&p](const std::string &f) { return p.rfind(f, 0) == 0; });
        if (!known) {
            rest.push_back(p);
        }
    }
    return rest;
}

bool mentions(const std::vector<std::string> &problems, const std::string &needle)
{
    for (const auto &p : problems) {
        if (p.find(needle) != std::string::npos) {
            return true;
        }
    }
    return false;
}

void dump(const char *what, const infrastructure::AnonymizationVerification &v)
{
    std::cerr << what << ": " << v.problems.size() << " problem(s)\n";
    for (const auto &p : v.problems) {
        std::cerr << "    " << p << "\n";
    }
}

}  // namespace

int main(int argc, char **argv)
{
    const fs::path fixture = argc > 1 ? fs::path(argv[1]) : fs::path("tests/fixtures/anonymized_library");
    if (!fs::is_directory(fixture)) {
        std::cerr << "fixture not found at " << fixture << " -- run from the repository root\n";
        return 1;
    }

    const fs::path root = seabass::testing::scratchRoot() / "seabass_anonymization_verifier_test";
    std::error_code ec;
    fs::remove_all(root, ec);
    fs::create_directories(root);
    const fs::path copy = root / "export";
    fs::copy(fixture, copy, fs::copy_options::recursive, ec);
    assert(!ec);

    const fs::path pdb = copy / "rekordbox" / "rekordbox" / "export.pdb";
    const fs::path pristinePdb = root / "export.pdb.pristine";
    fs::copy_file(pdb, pristinePdb, fs::copy_options::overwrite_existing, ec);
    assert(!ec);
    auto restorePdb = [&] {
        std::error_code e;
        fs::copy_file(pristinePdb, pdb, fs::copy_options::overwrite_existing, e);
        assert(!e);
    };

    // The clean copy must pass, or every "it refused" below proves
    // nothing -- a verifier that refuses everything would satisfy them all.
    {
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        const auto rest = beyondKnownBaseline(v.problems);
        if (!rest.empty()) {
            dump("clean copy, beyond the known baseline", v);
        }
        assert(rest.empty());
        assert(v.rekordboxTracksSampled > 0);
        assert(v.filesSwept > 0);
        // When this fires, the fixture has been regenerated clean: delete
        // knownDirtyFixtureFiles and every use of it, and go back to
        // asserting v.problems.empty() outright.
        if (v.problems.empty()) {
            std::cerr << "The fixture is clean now -- remove knownDirtyFixtureFiles from this test.\n";
            return 1;
        }
        std::cout << "case 1 (the fixture passes apart from its two known-dirty files) OK\n";
    }

    // Layout: anything the manifest does not account for is a leak,
    // because it was never anonymized by anything.
    {
        const fs::path stray = copy / "my-real-library.txt";
        std::ofstream(stray) << "real content";
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(!v.problems.empty());
        assert(mentions(v.problems, "my-real-library.txt"));
        fs::remove(stray);
        std::cout << "case 2 (an unexpected file at the top level is refused) OK\n";
    }

    // exportExt.pdb is on the allowlist now that its My Tag names can be
    // scrubbed (issue #1), so the NAME no longer refuses it -- and a
    // check that stopped at the name would let an unscrubbed one through
    // on the strength of being called the right thing. What refuses it is
    // its contents. Planted with real tag text in it, exactly as it
    // would arrive if the scrub had been skipped.
    {
        const fs::path stray = copy / "rekordbox" / "rekordbox" / "exportExt.pdb";
        std::ofstream(stray) << "Deep House\nPeak Time\nSecond Floor\nBuild up";
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(!v.problems.empty());
        // Refused for its CONTENTS, not merely for existing -- so one
        // single problem has to name both the file and the leak. Two
        // separate mentions() calls would both pass on the known-dirty
        // baseline, which already reports readable text in two other
        // files whatever this case plants.
        assert(std::any_of(v.problems.begin(), v.problems.end(), [](const std::string &p) {
            return p.find("exportExt.pdb") != std::string::npos
                && p.find("readable text") != std::string::npos;
        }));
        fs::remove(stray);
        std::cout << "case 3 (an unscrubbed exportExt.pdb is refused for its contents) OK\n";
    }

    // The outer level, which the case above used to cover and stopped
    // covering when exportExt.pdb moved onto the allowlist: anything
    // directly inside the rekordbox tree that is not a known directory
    // or a player settings file is refused by NAME, because nothing
    // anonymizes a file nothing knows about. Kept with a file that was
    // never on any allowlist, so it cannot be un-covered the same way
    // twice.
    {
        const fs::path stray = copy / "rekordbox" / "playlists3.sync";
        std::ofstream(stray) << "playlist names rekordbox keeps in sync state";
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(!v.problems.empty());
        assert(mentions(v.problems, "unexpected entry in the rekordbox tree"));
        assert(mentions(v.problems, "playlists3.sync"));
        fs::remove(stray);
        std::cout << "case 3b (an unexpected entry in the rekordbox tree is refused by name) OK\n";
    }

    // The other half of the same rule: a SCRUBBED one is accepted. Without
    // this, tightening the check back to a bare name refusal would leave
    // case 3 green and silently undo the issue -- no fixture would carry
    // My Tags again.
    {
        // Beside the fixture library this test was pointed at, so it
        // follows argv[1] rather than guessing at a build layout.
        const fs::path scrubbed = fixture.parent_path() / "exportExt.pdb";
        assert(fs::is_regular_file(scrubbed) && "the anonymized exportExt.pdb fixture is missing");
        const fs::path kept = copy / "rekordbox" / "rekordbox" / "exportExt.pdb";
        fs::copy_file(scrubbed, kept, fs::copy_options::overwrite_existing);
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(!mentions(v.problems, "exportExt.pdb"));
        fs::remove(kept);
        std::cout << "case 3c (a scrubbed exportExt.pdb is kept) OK\n";
    }

    // The same rule one level deeper, and the one that matters most of
    // the three. hm.db is Engine's play history: real titles, artists,
    // albums and paths, plus which set each track was played in, and
    // nothing in this project anonymizes it. The anonymizer removes it,
    // and #35 is about that removal being able to fail silently. It no
    // longer can -- but the check that catches a removal which failed
    // anyway had never been seen to fire, and the check inside
    // Database2 is newer than the two above.
    {
        const fs::path stray = copy / "engine" / "Database2" / "hm.db";
        std::ofstream(stray) << "play history: every real title this DJ played, and when";
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(!v.problems.empty());
        assert(mentions(v.problems, "hm.db"));
        fs::remove(stray);
        std::cout << "case 3d (a file with no anonymizer inside Database2 is refused) OK\n";
    }

    // Content: a real title and a real filename on a track the verifier
    // samples. Written through the app's own writer so the row is a real
    // row, not a hand-built one.
    {
        infrastructure::rekordbox::KaitaiRekordboxReader reader((copy / "rekordbox").string());
        const auto tracks = reader.readAll();
        assert(!tracks.empty());
        const std::uint32_t id = static_cast<std::uint32_t>(std::stoul(tracks.front().sourceId));

        infrastructure::rekordbox::PdbRowWriter writer(pdb.string());
        infrastructure::rekordbox::PdbRowWriter::TrackTextOverride text;
        text.title = "Blue Monday";
        assert(writer.overwriteTrackText(id, text));
        assert(writer.commit());

        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        if (v.problems.empty()) {
            dump("planted title", v);
        }
        assert(mentions(v.problems, "still has a real title"));
        restorePdb();
        std::cout << "case 4 (a real title on a sampled track is refused) OK\n";
    }

    {
        infrastructure::rekordbox::KaitaiRekordboxReader reader((copy / "rekordbox").string());
        const auto tracks = reader.readAll();
        const std::uint32_t id = static_cast<std::uint32_t>(std::stoul(tracks.front().sourceId));

        infrastructure::rekordbox::PdbRowWriter writer(pdb.string());
        infrastructure::rekordbox::PdbRowWriter::TrackTextOverride text;
        text.filename = "realsong.mp3";
        assert(writer.overwriteTrackText(id, text));
        assert(writer.commit());

        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(mentions(v.problems, "still has a real filename") || mentions(v.problems, "still has a real file path"));
        restorePdb();
        std::cout << "case 5 (a real filename on a sampled track is refused) OK\n";
    }

    // The case that matters most: the same leak, on the LAST track.
    //
    // The verifier used to check 200 tracks per catalog by default, which
    // on this 1161-track fixture left 83% of the rows unexamined -- a
    // real title planted at the end passed the gate reporting zero
    // problems. Both halves are asserted here: the default now catches
    // it, and a deliberately small sample still misses it, which is the
    // evidence for why the default changed.
    {
        infrastructure::rekordbox::KaitaiRekordboxReader reader((copy / "rekordbox").string());
        const auto tracks = reader.readAll();
        assert(tracks.size() > 400);
        const std::uint32_t lateId =
            static_cast<std::uint32_t>(std::stoul(tracks[tracks.size() - 1].sourceId));

        infrastructure::rekordbox::PdbRowWriter writer(pdb.string());
        infrastructure::rekordbox::PdbRowWriter::TrackTextOverride text;
        text.title = "Blue Monday";
        assert(writer.overwriteTrackText(lateId, text));
        assert(writer.commit());

        auto byDefault = infrastructure::verifyAnonymizedExport(copy.string());
        if (!mentions(byDefault.problems, "still has a real title")) {
            dump("leak on the last track, default settings", byDefault);
        }
        assert(mentions(byDefault.problems, "still has a real title"));

        auto sampled200 = infrastructure::verifyAnonymizedExport(copy.string(), 200);
        assert(!mentions(sampled200.problems, "still has a real title"));

        std::cout << "case 6 (a leak on the last track is caught by default, and missed at sample=200) OK\n";
        restorePdb();
    }

    // Every track really is examined, not merely more of them.
    {
        infrastructure::rekordbox::KaitaiRekordboxReader reader((copy / "rekordbox").string());
        const auto tracks = reader.readAll();
        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        assert(beyondKnownBaseline(v.problems).empty());
        assert(v.rekordboxTracksSampled == static_cast<int>(tracks.size()));
        std::cout << "case 7 (the default sweeps every track in the catalog: "
                  << v.rekordboxTracksSampled << ") OK\n";
    }

    // The reason the byte sweep exists: a leak in a file no reader parses
    // and in bytes no row points at. The waveform blobs are the purest
    // case -- nothing in this project reads their contents, so before the
    // sweep there was no check in the codebase that could have seen this.
    {
        fs::path blob;
        for (const auto &entry : fs::recursive_directory_iterator(copy / "engine", ec)) {
            if (entry.is_regular_file(ec) && entry.path().extension() == ".rgb") {
                blob = entry.path();
                break;
            }
        }
        assert(!blob.empty());
        const fs::path pristineBlob = root / "blob.pristine";
        fs::copy_file(blob, pristineBlob, fs::copy_options::overwrite_existing, ec);
        assert(!ec);

        {
            std::fstream out(blob, std::ios::binary | std::ios::in | std::ios::out);
            assert(out);
            const std::string planted = "Blue Monday by New Order";
            out.seekp(0);
            out.write(planted.data(), static_cast<std::streamsize>(planted.size()));
        }

        auto v = infrastructure::verifyAnonymizedExport(copy.string());
        const auto rest = beyondKnownBaseline(v.problems);
        if (rest.empty()) {
            dump("planted text in a waveform blob", v);
        }
        assert(!rest.empty());
        assert(mentions(rest, blob.filename().string()));
        assert(mentions(rest, "Blue Monday"));
        // And nothing that reads rows noticed, which is the whole point.
        assert(!mentions(rest, "still has a real title"));

        fs::copy_file(pristineBlob, blob, fs::copy_options::overwrite_existing, ec);
        assert(!ec);
        std::cout << "case 8 (text planted where no reader looks is caught by the byte sweep) OK\n";
    }

    // The byte sweep reads a SQLite file's own schema to know which words
    // are the database's rather than the user's, and it opens that file
    // through a URI. The output folder is the user's choice, and '#' or '%'
    // in it used to break the URI: the open failed without a sound, the
    // schema vocabulary came back empty, and schema text (the Engine
    // triggers' own messages) was reported as a leak. Same database, two
    // folders: the answer must not depend on the folder's name. ('?' is
    // not allowed in a Windows path, so it is not in the name.)
    {
        const fs::path db = copy / "engine" / "Database2" / "m.db";
        assert(fs::is_regular_file(db));
        const fs::path plainDir = root / "sweep-plain";
        const fs::path hostileDir = root / "Music #2 100%";
        fs::create_directories(plainDir, ec);
        fs::create_directories(hostileDir, ec);
        fs::copy_file(db, plainDir / "m.db", fs::copy_options::overwrite_existing, ec);
        assert(!ec);
        fs::copy_file(db, hostileDir / "m.db", fs::copy_options::overwrite_existing, ec);
        assert(!ec);

        const auto plain = infrastructure::readableTextInRawBytes(plainDir / "m.db");
        const auto hostile = infrastructure::readableTextInRawBytes(hostileDir / "m.db");
        assert(plain && hostile && "both copies must be readable, or this compares two failures");
        if (plain != hostile) {
            std::cerr << "sweep of the same m.db differs by folder name: " << plain->size() << " vs "
                      << hostile->size() << " unaccounted fragments\n";
        }
        assert(plain == hostile);
        std::cout << "case 9 (the byte sweep reads a database's schema whatever its folder is called) OK\n";
    }

    // What this check does when it cannot look. Every walk in here used
    // to hand an error_code to a std::filesystem iterator and never read
    // it, and an iterator that cannot open a directory returns end(): a
    // tree nothing could read was indistinguishable from a tree with
    // nothing in it, and the verdict is "no problems found".
    int skipped = 0;
#if !defined(_WIN32)
    if (::geteuid() != 0) {
        // A folder in the export that cannot be read.
        {
            const fs::path anlz = copy / "rekordbox" / "USBANLZ";
            assert(fs::is_directory(anlz));
            fs::permissions(anlz, fs::perms::none, fs::perm_options::replace);
            auto v = infrastructure::verifyAnonymizedExport(copy.string());
            fs::permissions(anlz, fs::perms::owner_all, fs::perm_options::replace);

            const auto rest = beyondKnownBaseline(v.problems);
            if (rest.empty()) {
                dump("a folder that could not be read", v);
            }
            assert(!rest.empty() && "a tree that could not be read is not a tree that is clean");
            assert(mentions(rest, "could not read") || mentions(rest, "stopped reading"));
            std::cout << "case 10 (a folder the check cannot read is refused, not counted as clean) OK\n";
        }

        // A file in the export that cannot be read: the sweep returned an
        // empty list for it, which is what a clean file returns.
        {
            const fs::path pdbFile = copy / "rekordbox" / "rekordbox" / "export.pdb";
            fs::permissions(pdbFile, fs::perms::none, fs::perm_options::replace);
            auto v = infrastructure::verifyAnonymizedExport(copy.string());
            fs::permissions(pdbFile, fs::perms::owner_read | fs::perms::owner_write, fs::perm_options::replace);

            assert(mentions(v.problems, "never swept")
                   && "a file nothing could read is not a file that was found clean");
            std::cout << "case 11 (a file the sweep cannot read is refused) OK\n";
        }
    } else {
        // Not "skipped": these two are the cases that prove the walks
        // report what they could not read, and a run that cannot make
        // them run has not checked that. Failing is what this project
        // does with a check that did not fully run, and the fix is in
        // the operator's hands: do not run the suite as root.
        std::cerr << "FAIL: cases 10 and 11 need permissions to bind, and this run is root. Run the suite as an "
                     "ordinary user.\n";
        return 1;
    }
#else
    // Windows has no chmod 000, so the two cases cannot be built there
    // at all. Counted and named rather than silently absent, so the lane
    // that runs this says what it did not check.
    skipped += 2;
    std::cerr << "SKIPPED cases 10 and 11 (a folder and a file that cannot be read): POSIX permissions only, so "
                 "the Linux lane is where they run.\n";
#endif

    // And the floor under all of it: an export with nothing in it swept
    // nothing, which is not the same as nothing being wrong.
    {
        const fs::path empty = root / "empty-export";
        fs::create_directories(empty);
        auto v = infrastructure::verifyAnonymizedExport(empty.string());
        assert(!v.ok && "an export this never looked inside must not pass");
        assert(mentions(v.problems, "proved nothing"));
        // And only for that reason. A tree that is not there is not a
        // tree that could not be read: a rekordbox-only export has no
        // engine/Database2, and reporting its absence as a leak would
        // throw a good export away.
        assert(!mentions(v.problems, "could not read")
               && "a directory that does not exist is not a directory this failed to read");
        std::cout << "case 12 (an export with nothing swept is refused, and only for that) OK\n";
    }

    // A path whose bytes cannot be read comes back as "could not read",
    // not as a file that was read and found clean.
    //
    // Which guard catches it, measured on this libstdc++ rather than
    // assumed: fs::file_size() fails first ("Is a directory"). Remove
    // that and the length comparison catches it, because the stream
    // opens on a directory here -- bool(in) is true -- and reads zero
    // bytes. Remove both and the read throws
    // "basic_filebuf::underflow error reading the file", which the catch
    // turns into the same answer. So this one case exercises all three
    // in turn, and the one thing none of them is provoked by is the
    // failure they were written for: a read that starts and then stops
    // partway, which needs a medium that fails mid-file.
    {
        const auto swept = infrastructure::readableTextInRawBytes(copy / "rekordbox");
        assert(!swept && "a path whose bytes could not be read is not a clean file");
        std::cout << "case 13 (a path whose bytes cannot be read says so) OK\n";
    }

    fs::remove_all(root, ec);
    // Said in the last line rather than left to whoever scrolls up: a
    // run that skipped the two cases proving the central claim is not
    // the same run as one that made them pass, and "all cases passed" on
    // its own reads as if it were.
    if (skipped > 0) {
        std::cout << "all cases passed, " << skipped << " skipped (see SKIPPED above)\n";
    } else {
        std::cout << "all cases passed\n";
    }
    return 0;
}
