#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Sebastian Kügler <sebas@kde.org>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

"""Build the two Seabass test libraries out of real music and real defects.

Every fixture this project has today is either a catalog with no audio at all
(tests/fixtures/anonymized_library) or bytes synthesised frame by frame
(tests/mp3_fixture.hpp). Both are useful and neither can answer the question
that keeps biting: what happens to a library that a human actually assembled
over fifteen years, on gear from three manufacturers, with every exporter
writing tags its own way.

So these two sets are real recordings, chosen for the shapes that break
matching, and then deliberately damaged in the ways this library was already
damaged. Every planted defect below was observed first, in the wild, with a
count -- see docs/test-libraries.md for the catalogue and where each was seen.

    A -- matching and metadata torture   (~35 tracks, fits any stick)
    B -- repair and cleanup torture      (~65 tracks)

Eight tracks are in both, so cross-stick sync has something to match.

Not everything can be planted here. Cues arrive when rekordbox imports the XML
this writes and exports it to a stick; catalog-level damage (an Engine row
whose sample rate will not decompress) is planted afterwards, on the exported
stick, by plant_defects.py. This script does the files and the XML.
"""

import argparse
import os
import random
import shutil
import subprocess
import sys
import unicodedata
import urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_library import read_tags, safe_component, xml_safe  # noqa: E402

# A planted defect is worth nothing if nobody can tell it is planted, so each
# one carries an id that the manifest, the expectations file and any test that
# asserts on it all share.
MANIFEST_HEADER = """# Seabass test library

Generated by tools/library-build/make_test_library.py. Real audio, real
defects. Do not "fix" anything in here: every oddity is deliberate and is
referenced by id from docs/test-libraries.md.

"""


def run(command, **kwargs):
    return subprocess.run(command, check=False, capture_output=True, **kwargs)


def decode_to_wav(source, destination):
    if source.lower().endswith(".flac"):
        with open(destination, "wb") as handle:
            result = subprocess.run(
                ["flac", "-d", "-c", "--totally-silent", source], stdout=handle, stderr=subprocess.PIPE, check=False
            )
        return result.returncode == 0
    result = run(["afconvert", "-f", "WAVE", "-d", "LEI16", source, destination])
    return result.returncode == 0


def encode_mp3(wav, destination, args):
    """lame, with whatever shape this particular fixture needs."""
    result = run(["lame", "--quiet", *args, wav, destination])
    return result.returncode == 0 and os.path.exists(destination)


def nfd(text):
    """macOS spells filenames decomposed; a stick spells them composed.

    The pair is what makes "the same name" two different byte strings, which is
    the bug e2e/vsticks/vtest.sparseimage was built for.
    """
    return unicodedata.normalize("NFD", text)


class TestLibraryBuilder:
    def __init__(self, source, out_dir, seed=20260918):
        self.source = os.path.expanduser(source)
        self.out_dir = os.path.expanduser(out_dir)
        self.random = random.Random(seed)  # same library every run
        self.notes = []
        self.scratch = os.path.join(self.out_dir, ".scratch")

    def note(self, set_name, defect_id, path, what):
        self.notes.append((set_name, defect_id, os.path.relpath(path, self.out_dir), what))

    # -- picking real material -------------------------------------------

    def candidates(self):
        """Every mp3/m4a in the source library, with its tags."""
        found = []
        for base in ("Tracks",):
            root = os.path.join(self.source, base)
            for dirpath, _, filenames in os.walk(root):
                for name in filenames:
                    if os.path.splitext(name)[1].lower() not in (".mp3", ".m4a"):
                        continue
                    path = os.path.join(dirpath, name)
                    if os.path.getsize(path) < 200_000:
                        continue  # the broken ones have their own slot below
                    found.append(path)
        found.sort()
        return found

    def flac_candidates(self):
        root = os.path.join(self.source, "Lossless")
        found = []
        for dirpath, _, filenames in os.walk(root):
            for name in filenames:
                if name.lower().endswith(".flac"):
                    found.append(os.path.join(dirpath, name))
        found.sort()
        return found

    def pick(self, pool, predicate, count, used):
        """Real tracks whose names carry the shapes that break matching."""
        chosen = []
        for path in pool:
            if path in used or not predicate(path):
                continue
            chosen.append(path)
            used.add(path)
            if len(chosen) == count:
                break
        return chosen

    # -- the sets ---------------------------------------------------------

    def build(self):
        os.makedirs(self.scratch, exist_ok=True)
        pool = self.candidates()
        flacs = self.flac_candidates()
        if not pool:
            sys.exit(f"no source tracks under {self.source}/Tracks")

        used = set()
        shared = self.pick(pool, lambda p: True, 8, used)

        a_dir = os.path.join(self.out_dir, "TestA")
        b_dir = os.path.join(self.out_dir, "TestB")
        for directory in (a_dir, b_dir):
            os.makedirs(directory, exist_ok=True)

        self.build_a(a_dir, pool, flacs, used, shared)
        self.build_b(b_dir, pool, flacs, used, shared)

        shutil.rmtree(self.scratch, ignore_errors=True)
        for set_name, directory in (("A", a_dir), ("B", b_dir)):
            path, count = self.write_xml(set_name, directory)
            print(f"  {os.path.basename(path)}: {count} track(s)")
        self.write_manifest()

    def copy_in(self, source, directory, name=None):
        destination = os.path.join(directory, name or os.path.basename(source))
        os.makedirs(os.path.dirname(destination), exist_ok=True)
        shutil.copy2(source, destination)
        return destination

    def build_a(self, directory, pool, flacs, used, shared):
        name = "A"

        for path in shared:
            self.copy_in(path, directory)
            self.note(name, "A0-shared", os.path.join(directory, os.path.basename(path)),
                       "also in B, so cross-stick sync has a match")

        # The shapes the matcher gets wrong, in real spellings.
        for defect, predicate, count, what in (
            ("A1-feat", lambda p: "feat." in os.path.basename(p).lower(), 3,
             "a 'feat.' spelling: matching has to survive it"),
            ("A2-remix", lambda p: "remix" in os.path.basename(p).lower(), 3,
             "a remix suffix, the other half of the same problem"),
            ("A3-accents", lambda p: any(ord(c) > 127 for c in os.path.basename(p)), 3,
             "non-ASCII in the name"),
            ("A4-multiartist", lambda p: os.path.basename(p).count(",") >= 2, 2,
             "three or more artists in one field"),
        ):
            for path in self.pick(pool, predicate, count, used):
                self.note(name, defect, self.copy_in(path, directory), what)

        source = self.pick(pool, lambda p: True, 1, used)[0]

        # NFD vs NFC: the same name, two byte strings.
        decomposed = self.copy_in(source, directory, nfd("Tiësto, Böhmer - Røyksopp Café.mp3"))
        self.note(name, "A5-nfd", decomposed, "filename is NFD-decomposed; a stick will spell it NFC")

        # A path no MAX_PATH-era code survives.
        deep = os.path.join(directory, *["a-folder-name-of-forty-characters-long!!" for _ in range(6)])
        os.makedirs(deep, exist_ok=True)
        self.note(name, "A6-longpath", self.copy_in(source, deep), "path is over 300 characters")

        # A trailing space: Windows strips it and then cannot find the file.
        trailing = self.copy_in(source, directory, "Trailing space .mp3")
        self.note(name, "A7-trailingspace", trailing, "filename component ends in a space")

        # Bitrates and VBR. The suite has never seen anything but 128 CBR.
        wav = os.path.join(self.scratch, "a.wav")
        if decode_to_wav(source, wav):
            for defect, args, label in (
                ("A8-cbr128", ["-b", "128", "--cbr"], "128 kbps CBR"),
                ("A9-cbr192", ["-b", "192", "--cbr"], "192 kbps CBR"),
                ("A10-vbr-noxing", ["-V", "2", "-t"], "true VBR with NO Xing header: duration must be estimated"),
            ):
                destination = os.path.join(directory, f"{defect}.mp3")
                if encode_mp3(wav, destination, args):
                    self.note(name, defect, destination, label)

            # 44.1 / 48 / 96 kHz, 16 and 24 bit, as FLAC -- no fixture has ever
            # offered a sample rate other than 44100.
            for defect, rate, label in (
                ("A11-flac48", "48000", "FLAC at 48 kHz"),
                ("A12-flac96", "96000", "FLAC at 96 kHz, 24-bit"),
            ):
                destination = os.path.join(directory, f"{defect}.flac")
                if run(["afconvert", "-f", "flac", "-d", f"flac@{rate}", source, destination]).returncode == 0:
                    self.note(name, defect, destination, label)

        if flacs:
            plain = self.copy_in(flacs[0], directory, "A13-flac-vorbis-only.flac")
            self.note(name, "A13-flac-vorbis", plain, "FLAC carrying Vorbis comments only")
            if len(flacs) > 1:
                twin = self.copy_in(flacs[1], directory, "A14-flac-twin.flac")
                self.note(name, "A14-flac-twin", twin,
                           "the FLAC half of an mp3/FLAC pair: cue sync has to cross formats")

        # Tags that are legal in a file and illegal in XML, or simply absent.
        self.plant_tag_defects(name, directory, source)

    def plant_tag_defects(self, set_name, directory, source):
        from mutagen.id3 import ID3, TIT2, TPE1

        stripped = self.copy_in(source, directory, "B?-untagged.mp3" if set_name == "B" else "A15-untagged.mp3")
        try:
            tags = ID3(stripped)
            tags.delete()
            tags.save(stripped)
            self.note(set_name, f"{set_name}15-untagged", stripped,
                       "no tags at all: identity falls back to the filename")
        except Exception:
            pass

        control = self.copy_in(source, directory, f"{set_name}16-control-byte.mp3")
        try:
            tags = ID3(control)
            # The exact shape found on the real stick: a form feed inside an
            # artist frame. XML 1.0 cannot represent it, and one occurrence
            # makes a whole collection file unimportable.
            tags.add(TPE1(encoding=3, text="A�\x0c"))
            tags.add(TIT2(encoding=3, text="Control byte in the artist frame"))
            tags.save(control)
            self.note(set_name, f"{set_name}16-controlbyte", control,
                       "artist tag holds 0x0C, which XML cannot encode")
        except Exception:
            pass

    def build_b(self, directory, pool, flacs, used, shared):
        name = "B"

        for path in shared:
            self.copy_in(path, directory)

        for path in self.pick(pool, lambda p: True, 40, used):
            self.copy_in(path, directory)

        source = self.pick(pool, lambda p: True, 1, used)[0]

        # A duplicate pair where BOTH copies have their own audio and NEITHER
        # has cues. rig check W6 needs exactly this and has to plant it itself
        # today (tools/rig_plant_repairable.cpp).
        first = self.copy_in(source, os.path.join(directory, "folderA"))
        second = self.copy_in(source, os.path.join(directory, "folderB"))
        self.note(name, "B1-dup-nocues", first, "duplicate pair, both files present, no cues (rig W6)")
        self.note(name, "B2-dup-nocues", second, "the other half of B1")

        # Unreferenced: on the stick, in no catalog. The XML simply will not
        # list these two.
        orphan = self.copy_in(source, os.path.join(directory, "unreferenced"), "B3-orphan.mp3")
        self.note(name, "B3-orphan", orphan, "audio no catalog references (rig W8)")

        # A file that is the right size and entirely zero bytes. 114 of these
        # were in the real library, and 109 were the only copy of a recording.
        zeroed = os.path.join(directory, "B4-zero-filled.mp3")
        with open(zeroed, "wb") as handle:
            handle.write(b"\0" * 12_000_000)
        self.note(name, "B4-zerofilled", zeroed, "right size, not one non-zero byte; nothing can decode it")

        # Truncated: a header and then nothing, so no probe can find a
        # duration or a sample rate.
        truncated = os.path.join(directory, "B5-truncated.mp3")
        with open(source, "rb") as src, open(truncated, "wb") as dst:
            dst.write(src.read(45_000))
        self.note(name, "B5-truncated", truncated, "truncated to 45 KB: no duration, no sample rate")

        # A FLAC whose header says one thing and whose stream stops early.
        if flacs:
            broken = os.path.join(directory, "B6-flac-truncated.flac")
            with open(flacs[0], "rb") as src, open(broken, "wb") as dst:
                dst.write(src.read(120_000))
            self.note(name, "B6-flac-truncated", broken, "FLAC cut mid-stream")

            pair_flac = self.copy_in(flacs[0], directory, "B7-crossformat.flac")
            wav = os.path.join(self.scratch, "b.wav")
            if decode_to_wav(flacs[0], wav):
                pair_mp3 = os.path.join(directory, "B7-crossformat.mp3")
                if encode_mp3(wav, pair_mp3, ["-b", "320", "--cbr"]):
                    self.note(name, "B7-crossformat", pair_mp3,
                               "same recording as B7-crossformat.flac: dedup and cue sync across formats")
            self.note(name, "B7-crossformat-flac", pair_flac, "the FLAC half of B7")

        # Artwork present on one copy, absent on its twin.
        self.plant_tag_defects(name, directory, source)

    def write_xml(self, set_name, directory):
        """A rekordbox collection XML for one set, cues included.

        Cues cannot be written into an audio file, so this is how they get
        planted: rekordbox imports them here, and exporting the playlist to a
        stick is what turns them into the ANLZ sections and Engine rows the
        tests actually read. The junk ones are deliberate -- a memory cue at
        0:00 and one at 0.5 s, which is what Engine's own auto-placed main_cue
        looks like on every real stick.

        Files under unreferenced/ are left out on purpose: "audio no catalog
        mentions" is a fixture shape in its own right (rig W8).
        """
        import xml.etree.ElementTree as ET

        root = ET.Element("DJ_PLAYLISTS", {"Version": "1.0.0"})
        ET.SubElement(root, "PRODUCT", {"Name": "Seabass", "Version": "0.1", "Company": "Seabass"})
        collection = ET.SubElement(root, "COLLECTION")

        entries = []
        for dirpath, dirnames, filenames in os.walk(directory):
            dirnames[:] = [d for d in dirnames if d != "unreferenced"]
            for filename in sorted(filenames):
                if os.path.splitext(filename)[1].lower() not in (".mp3", ".m4a", ".flac", ".wav"):
                    continue
                entries.append(os.path.join(dirpath, filename))
        entries.sort()

        cue_plan = {
            # index into the sorted file list -> what to put on it
            0: [("hot", 1, 30.765, "#FF0017"), ("hot", 2, 75.259, "#00C4FF")],
            1: [("memory", -1, 0.0, "")],       # junk: exactly 0:00
            2: [("memory", -1, 0.539, "")],     # junk: Engine's main_cue drift
            3: [("hot", 1, 12.5, "#FF0017"), ("memory", -1, 61.0, "")],
            4: [("loop", 3, 90.0, "#33FF00")],
        }

        track_ids = {}
        for index, path in enumerate(entries, 1):
            copy = read_tags(path)
            attributes = {
                "TrackID": str(index),
                "Name": copy.title or os.path.splitext(os.path.basename(path))[0],
                "Artist": copy.artist,
                "Album": copy.album,
                "Kind": {".mp3": "MP3 File", ".m4a": "M4A File", ".flac": "FLAC File", ".wav": "WAV File"}[
                    os.path.splitext(path)[1].lower()
                ],
                "TotalTime": str(int(copy.duration)),
                "Location": "file://localhost" + urllib.parse.quote(path, safe="/"),
            }
            if copy.bitrate:
                attributes["BitRate"] = str(copy.bitrate)
            # A tag can hold bytes XML cannot; the fixture that carries one on
            # purpose must not make its own collection file unimportable.
            attributes = {k: xml_safe(v) if isinstance(v, str) else v for k, v in attributes.items()}
            attributes["Location"] = "file://localhost" + urllib.parse.quote(path, safe="/")
            element = ET.SubElement(collection, "TRACK", attributes)
            track_ids[path] = str(index)

            for kind, num, start, color in cue_plan.get(index - 1, []):
                mark = {"Name": "", "Type": "4" if kind == "loop" else "0", "Start": f"{start:.3f}"}
                if kind == "loop":
                    mark["End"] = f"{start + 4.0:.3f}"
                mark["Num"] = str(num if kind != "memory" else -1)
                if color:
                    mark["Red"], mark["Green"], mark["Blue"] = (
                        str(int(color[1:3], 16)), str(int(color[3:5], 16)), str(int(color[5:7], 16))
                    )
                ET.SubElement(element, "POSITION_MARK", mark)

        collection.set("Entries", str(len(entries)))

        playlists = ET.SubElement(root, "PLAYLISTS")
        root_node = ET.SubElement(playlists, "NODE", {"Name": "ROOT", "Type": "0", "Count": "1"})
        leaf = ET.SubElement(
            root_node,
            "NODE",
            {"Name": f"Seabass test {set_name}", "Type": "1", "KeyType": "0", "Entries": str(len(entries))},
        )
        for path in entries:
            ET.SubElement(leaf, "TRACK", {"Key": track_ids[path]})

        out_path = os.path.join(self.out_dir, f"seabass-test-{set_name.lower()}.xml")
        ET.ElementTree(root).write(out_path, encoding="UTF-8", xml_declaration=True)
        return out_path, len(entries)

    def write_manifest(self):
        path = os.path.join(self.out_dir, "MANIFEST.md")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(MANIFEST_HEADER)
            for set_name in ("A", "B"):
                rows = [n for n in self.notes if n[0] == set_name]
                handle.write(f"\n## Seabass test {set_name}\n\n")
                handle.write("| id | file | what is wrong with it |\n|---|---|---|\n")
                for _, defect_id, relative, what in rows:
                    handle.write(f"| `{defect_id}` | `{relative}` | {what} |\n")
        # A stick carrying real music must say so, per docs/real-data-testing.md.
        with open(os.path.join(self.out_dir, "SET.txt"), "w", encoding="utf-8") as handle:
            handle.write(
                "THIS DATA IS NOT ANONYMIZED.\n\n"
                "Real recordings from a real collection, with deliberate defects planted.\n"
                "Do not commit it, and do not send it anywhere. See MANIFEST.md.\n"
            )
        return path


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", default="~/Music/WhalesharkLibrary", help="library to draw real tracks from")
    parser.add_argument("--out", default="~/Music/SeabassTestLibrary", help="where to build the test sets")
    args = parser.parse_args()

    builder = TestLibraryBuilder(args.source, args.out)
    builder.build()

    for set_name in ("A", "B"):
        directory = os.path.join(builder.out_dir, f"Test{set_name}")
        total = 0
        count = 0
        for dirpath, _, filenames in os.walk(directory):
            for filename in filenames:
                total += os.path.getsize(os.path.join(dirpath, filename))
                count += 1
        print(f"Test{set_name}: {count} file(s), {total / 2**20:.0f} MB")
    print(f"planted: {len(builder.notes)} documented defect(s)")
    print(f"manifest: {os.path.join(builder.out_dir, 'MANIFEST.md')}")


if __name__ == "__main__":
    main()
