// SPDX-FileCopyrightText: 2026 Sebastian Kügler <sebas@kde.org>
//
// SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

// Replaces every My Tag and tag category name in an exportExt.pdb with a
// placeholder, in place.
//
//   anonymize_export_ext <exportExt.pdb>
//
// Issue #1: the library anonymizer DELETED exportExt.pdb, because My Tag
// names are free text a DJ typed and nothing could anonymize them. No
// committed fixture carried one, so nothing Seabass does with My Tags
// was ever exercised against real-shaped data. This is the missing
// piece, kept as a tool rather than buried in the anonymizer so a
// fixture can be regenerated from a real stick without running a whole
// export.
//
// The rewrite preserves each name's byte length, so a placeholder longer
// than the name it replaces is truncated: "Tag 12" over "Beat" becomes
// "Tag ". Several short tags therefore collapse onto the same
// placeholder, and each name's LENGTH survives. That is the same trade
// every other placeholder in the anonymizer makes, and it is the reason
// this cannot be used to hide anything whose length is itself the
// secret.
//
// Prints what it did and leaves the file untouched if it could not
// commit, so a failure cannot half-anonymize a file somebody then ships.

#include <cstdio>
#include <filesystem>
#include <iostream>
#include <string>

#include "infrastructure/paths/utf8_path.hpp"
#include "infrastructure/rekordbox/pdb_row_writer.hpp"

namespace fs = std::filesystem;
using seabass::pathFromUtf8;
using seabass::pathToUtf8;
using seabass::infrastructure::rekordbox::PdbRowWriter;

int main(int argc, char **argv)
{
    if (argc < 2) {
        std::cout << "usage: anonymize_export_ext <exportExt.pdb>\n";
        return 2;
    }
    const fs::path path = pathFromUtf8(argv[1]);
    if (!fs::is_regular_file(path)) {
        std::cout << "not a file: " << pathToUtf8(path) << "\n";
        return 2;
    }
    try {
        PdbRowWriter writer(pathToUtf8(path), PdbRowWriter::Format::ExportExt);
        // Zero-padded, matching the anonymizer's own placeholder() so
        // the two writers of this file cannot be told apart by what they
        // wrote. They disagreed: this produced "Tag 1" and the anonymizer
        // "Tag 000", while comments in two places claimed the committed
        // fixture was what the anonymizer produces.
        int leftAlone = 0;
        const int rewritten = writer.overwriteAllTagNames(
            [](size_t i) {
                char buf[16];
                std::snprintf(buf, sizeof(buf), "%03zu", i);
                return "Tag " + std::string(buf);
            },
            &leftAlone);
        // Rekordbox leaves renamed and deleted tag names in page slack,
        // and a fixture regenerated by this tool has to be as clean as
        // one the anonymizer produces.
        const int zeroed = writer.zeroUnusedSpace();
        if (rewritten == 0) {
            // Not silently fine: either the file holds no tags, or it was
            // opened as the wrong format, and those look identical from
            // here. Saying so beats writing nothing and reporting success.
            std::cout << "no tag rows found in " << pathToUtf8(path)
                      << " -- either it carries none, or it is not an exportExt.pdb\n";
            return 1;
        }
        // A row this could not rewrite kept the name it already had, and
        // that name is a My Tag somebody typed. This tool regenerates
        // the committed fixture, so a partial scrub would put a real
        // name into a file that ships in this repository -- and
        // "rewrote 27 tag name(s)" would read as success while it
        // happened.
        if (leftAlone > 0) {
            std::cout << "refusing to write " << pathToUtf8(path) << ": " << leftAlone << " of "
                      << (rewritten + leftAlone) << " tag row(s) could not be rewritten and still hold their real "
                      << "names. The file was left exactly as it was.\n";
            return 1;
        }
        if (!writer.commit()) {
            std::cout << "refused to write: the file was left exactly as it was\n";
            return 1;
        }
        std::cout << "rewrote " << rewritten << " tag name(s) and cleared " << zeroed
                  << " byte(s) of free space in " << pathToUtf8(path.filename()) << "\n";
        return 0;
    } catch (const std::exception &e) {
        std::cout << "error: " << e.what() << "\n";
        return 1;
    }
}
