#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Sebastian Kügler <sebas@kde.org>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

"""Writes src/application/nfc_compositions.inc, the table normalizedPathKey()
composes decomposed filenames with.

macOS stores names on FAT/exFAT decomposed: a stick restored there carries
"e" + U+0301 where the backup held "é". Without this table the two are
different keys, which is the dangerous direction -- a referenced file reads
as unreferenced, and unreferenced files are what Seabass offers to delete.

Every row comes from Python's own Unicode database rather than being typed
out: for each code point whose canonical decomposition is a base plus one
combining mark, the pair is kept only when NFC composes it back, which is
what leaves out the composition exclusions (U+0958..U+095F and friends).
Run from the repository root; check the diff in, the build does not run it.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path("src/application/nfc_compositions.inc")


def compositions() -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    for cp in range(0x20, 0x10000):
        char = chr(cp)
        decomposition = unicodedata.decomposition(char)
        # Canonical only: a compatibility decomposition ("<font> ...") is a
        # different character, not a different spelling of one.
        if not decomposition or decomposition.startswith("<"):
            continue
        parts = decomposition.split()
        if len(parts) != 2:
            continue
        base, mark = int(parts[0], 16), int(parts[1], 16)
        if base > 0xFFFF or mark > 0xFFFF:
            continue
        if unicodedata.normalize("NFC", chr(base) + chr(mark)) != char:
            continue  # a composition exclusion
        rows.append((base, mark, cp))
    rows.sort()
    return rows


def main() -> None:
    rows = compositions()
    if len(rows) < 800:
        sys.exit(f"only {len(rows)} compositions found; refusing to write a table that small")
    # Assembled rather than written out, so that this file is not read as
    # carrying these tags itself. It has its own header above; a second,
    # literal set further down makes `reuse lint` report the whole file as
    # having no licensing information at all, which is what it did.
    tag = "SPDX"
    lines = [
        f"// {tag}-FileCopyrightText: 2026 Sebastian Kügler <sebas@kde.org>",
        "//",
        f"// {tag}-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL",
        "",
        "// Generated by tools/generate_nfc_compositions.py from Python's Unicode",
        f"// database ({unicodedata.unidata_version}). Do not edit by hand.",
        "//",
        "// {base code point, combining mark, the character they compose to},",
        "// sorted, so normalizedPathKey() can binary-search it.",
        "",
        "// clang-format off",
        f"constexpr NfcComposition NfcCompositions[] = {{  // {len(rows)} pairs",
    ]
    for base, mark, composed in rows:
        lines.append(f"    {{0x{base:04X}, 0x{mark:04X}, 0x{composed:04X}}},")
    lines.append("};")
    lines.append("// clang-format on")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} pairs, Unicode {unicodedata.unidata_version})")


if __name__ == "__main__":
    main()
